### ISSUE TITLE
damagecore's `damage` type uses an invalid type ID

### ISSUE THREAD

**Issue by AbigailBuccaneer** [sirpapate/damagecore#3]
In E2, [type IDs must be one character other than 'x', or three characters and begin with an x](https://github.com/wiremod/wire/commit/3d6ff50a37d9c91c542cf58895623a5394561289). The damage type's ID is `dmg`. This breaks things like E2Helper, and would break extra hard if another extension added a type with ID `d` or `m` or `g`.

I've just added a check to Wiremod to prevent this kind of thing from happening, which means that in the July 2018 Release, instead of damagecore breaking E2Helper, it will instead fail to load with the error:

> There was an error loading the custom/damagecore.lua extension. Please report this to its developer.
`entities/gmod_wire_expression2/core/custom/damagecore.lua:95: malformed type ID 'dmg' - type IDs must be one character long, or three characters long starting with an x`

**Comment by brandonsturgeon** [comment]
Hey @AbigailBuccaneer ! I was just tracking down this problem. Is there a wiremod branch with this fix already implemented?

**Comment by brandonsturgeon** [comment]
Further, how hard would it be to fix this? I don't know much about damage types, but I imagine these two lines are suspect:

https://github.com/sirpapate/damagecore/blob/master/lua/entities/gmod_wire_expression2/core/custom/damagecore.lua#L95
https://github.com/sirpapate/damagecore/blob/master/lua/entities/gmod_wire_expression2/core/custom/damagecore.lua#L112

**Comment by sarahsturgeon** [comment]
Opened PR #4 to fix this issue.

**Comment by sirpapate** [comment]
Thanks for the report and sorry for the delay!

I changed the type to "xdm"
